### ISSUE TITLE
Import problem with type wallet.*

### ISSUE THREAD

**Issue by thge** [juanii/OnePIF#1]
Importing items from 1Password for Windows 4.6.2.626 pif file fails for all entries with `"typeName":"wallet.*"`, like `wallet.onlineservices.GenericAccount` or `wallet.computer.Database`. After importing such entries the user name is empty and the password is set to "{PASSWORD}". All other information is imported correctly as string field contents.

After changing the type to "webforms.WebForm" the password is imported correctly but the user name is still empty.

Example entry:
`{"keyID":"075A7A68E945418DA04518011F111BA8","locationKey":"","typeName":"wallet.computer.Database","location":"","uuid":"9DEE69B496E042EEB21C33335DEF58E8","createdAt":1466422652,"securityLevel":"SL5","title":"suitecrm","updatedAt":1466422680,"txTimestamp":1466422680,"contentsHash":"9c8847c6","secureContents":{"sections":[{"title":"","name":"","fields":[{"k":"menu","n":"database_type","v":"mysql","t":"Type"},{"k":"string","n":"hostname","v":"hhhhhhhh","t":"Server"},{"k":"string","n":"port","v":"","t":"Port"},{"k":"string","n":"database","v":"dddddddd","t":"Database"},{"k":"string","n":"username","v":"uuuuuuuu","t":"Username"},{"k":"concealed","n":"password","v":"xxxxxxxxxxxxxxx","t":"Password"},{"k":"string","n":"sid","v":"","t":"SID"},{"k":"string","n":"alias","v":"","t":"Alias"},{"k":"string","n":"options","v":"","t":"Connection options"}]}],"database_type":"mysql","hostname":"hhhhhhhh","database":"dddddddd","username":"uuuuuuuu","password":"xxxxxxxxxxxxxxx"}}`

Thanks for your work!

**Comment by juanii** [comment]
Hello and thank you very much for your feedback.

I'll split your issue in two parts:

* Wrong password: the plugin maps the field considered by 1P as the "main" item password to the standard KeePass password field, but also tries to keep the original 1P field (with the `{PASSWORD}` placeholder as value, so the two fields will always contain the same data). In your case the two field names match (either because it was manually edited or older 1P versions used a capitalized title) and so the password field is set twice, overwriting the original password with the placeholder. It's a huge mistake not to check for that condition, so I'm fixing it and releasing a new version ASAP.

* Empty username: I'd call this is a missing feature, not a bug :) as stated in the README, I'm still working in the mapping of 1P fields to KeePass fields. There are different things that might be considered an item's username and password. The Database case is pretty straightforward, but for example 1P Server items can contain *two* password fields (and only one is considered *the* item's password field by 1P). OTOH Software License items don't contain any fields matching the concept of username and password. I begun this mapping work only a few days ago and passwords are (sometimes :) properly mapped, but usernames and URLs are still missing. Expect this to be done sometime soon.

Thank you again for using the plugin and sending the feedback.

**Comment by juanii** [comment]
The overwritten password bug is fixed and a new version 0.3.3 is available to download. Please check again in a few days for upcoming releases addressing the username field mapping. Thanks again for your report!

~~Given you have a vault with legacy item types (like `wallet.onlineservices.GenericAccount`) it would be great if you can provide (redacted) samples of these item types, ideally with all template fields populated, so I can add support for them. I couldn't find good samples online and my license is for 1P6 for macOS/1P4 for Windows so I can't run older versions.~~
Edit: just found the e-mail with my 1P4 license key and turns out it included a 1P3 license for free, so I can generate all the legacy sample data I need.

Regards.
