### ISSUE TITLE
Plugin incomatible with KeePass 2.38

### ISSUE THREAD

**Issue by kunalnagar** [juanii/OnePIF#4]
Plugin is not compatible with the version of KeePass?

Plugin version: 0.5.0
KeePass version: 2.38
Ubuntu 18.04.2 LTS

![image](https://user-images.githubusercontent.com/2741371/61459968-75001a00-a98b-11e9-9ebb-5d1db3ed585b.png)

**Comment by juanii** [comment]
Hello,

Actually I successfully used (can't say I really _tested_ it) the plugin with KeePass 2.38, though I think it was in Ubuntu 16.04.
I'll try to use it with Ubuntu 18.04.2 as soon as I can. In the meantime, if you have the knowledge to run commands from a terminal, could you please execute KeePass with the --debug flag? This will create a temporary file with the compilation output that would give me a good idea why it's failing. Also providing more information about the error would be useful: does it fail to compile (i.e. when you launch KeePass you get a compatibility error) or fails (how?) when trying to import a vault?

Thanks for reporting the error.

**Comment by juanii** [comment]
Just tested this. You're right it doesn't compile out of the box, but as stated in the [KeePass 2.x Plugins page](https://keepass.info/help/v2/plugins.html), on some Linux systems the package `mono-complete` is required and this seems to be the case because the plugin compiled just fine after installing that package, so I'll make a remark in the documentation and close this issue.

Not sure how to do it using the Ubuntu Software GUI, but from the terminal you can `sudo apt-get install mono-complete` to install the package and the plugin should start working.

Edit: typo.
